apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-conf
  annotations:
      description: |-
        Holds the custom ara.cnf used to start the server for ARA
  labels:
    app: ara
    ara.component: mysql
data:
  ara.cnf: |-
    [mysqld]
    port=3306
    autocommit=OFF
    character-set-server=utf8
    sql_mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
    default_storage_engine=innodb
    innodb_file_format=BARRACUDA
    innodb_file_format_max=BARRACUDA
    #innodb_log_file_size=50M
    # It is recommended that innodb_buffer_pool_size is configured to 50 to 75 percent of system memory.
    #innodb_buffer_pool_size=2033M
    innodb_large_prefix
    innodb_file_per_table
    #innodb-use-native-aio=0
    innodb-flush-method=fsync
    [client]
    port=3306